#pragma once

#include "approximation.hpp"
#include "differentiation_integration.hpp"
#include "eigen_approx.hpp"
#include "errors.hpp"
#include "interpolation.hpp"
#include "linear_algebra.hpp"
#include "nonlinear.hpp"
#include "ode.hpp"
#include "pde.hpp"
#include "quantum.hpp"
#include "roots.hpp"
#include "special_functions.hpp"
#include "types.hpp"
